### ISSUE TITLE
What score can R2CNN get?

### ISSUE THREAD

**Issue by Bonsen** [KeremTurgutlu/airbus#1]
It seems that mask-rcnn can get 0.92 in public LB.
What about R2CNN?

**Comment by KeremTurgutlu** [comment]
Hi, 

I am currently waiting for the actual test set to make my first submission. But as far as I read online on papers R2CNN seems promising or in general approaching to the problem as object detection with angles. So rather than learning only offsets cx,cy,w,h we can also learn angle offset. I guess after that all you need to do is filling the bounding box. At the moment i will try that approach with SSD network and see how it goes but any object detection network can be manipulated like that.

Best
